import {
  Heart,
  HeartPulse,
  ShieldPlus,
  Footprints,
  Wind,
  Ghost,
  Droplets,
  Waves,
  Infinity as InfinityIcon,
  Timer,
  TimerOff,
  Gauge,
  Shield,
  Mountain,
  Castle,
  Zap,
  BatteryCharging,
  CloudLightning,
  Brain,
  Sparkles,
  Wand2,
  Activity,
  Flame,
  ShieldAlert,
  Expand,
  CircleDot,
  Orbit,
  Eye,
  Crosshair,
  Target,
  Biohazard,
  FlaskConical,
  Skull,
  type LucideIcon,
} from 'lucide-react';

const ICON_BY_NAME: Record<string, LucideIcon> = {
  Heart,
  HeartPulse,
  ShieldPlus,
  Footprints,
  Wind,
  Ghost,
  Droplets,
  Waves,
  Infinity: InfinityIcon,
  Timer,
  TimerOff,
  Gauge,
  Shield,
  Mountain,
  Castle,
  Zap,
  BatteryCharging,
  CloudLightning,
  Brain,
  Sparkles,
  Wand2,
  Activity,
  Flame,
  ShieldAlert,
  Expand,
  CircleDot,
  Orbit,
  Eye,
  Crosshair,
  Target,
  Biohazard,
  FlaskConical,
  Skull,
};

/**
 * Resolve a Lucide icon component by its PascalCase name (stored in the perk
 * catalog as e.g. `'Heart'`, `'ShieldPlus'`). Falls back to `CircleDot` for
 * unknown names so the UI never crashes.
 */
export function resolvePerkIcon(name: string): LucideIcon {
  return ICON_BY_NAME[name] ?? CircleDot;
}
